const TOPICS = {
  chem:     {name:"Chemistry review: atoms & bonds", short:"Chem review"},
  water:    {name:"Water, polarity & bonds",      short:"Water & polarity"},
  groups:   {name:"Carbon & functional groups",   short:"Functional groups"},
  build:    {name:"Monomers, polymers & reactions", short:"Build & break"},
  carbs:    {name:"Carbohydrates",                short:"Carbs"},
  lipids:   {name:"Lipids",                       short:"Lipids"},
  proteins: {name:"Proteins",                     short:"Proteins"},
  nucleic:  {name:"Nucleic acids",                short:"Nucleic acids"},
  frq:      {name:"FRQ skills & data",            short:"FRQ skills"}
};

// MCQ: {id, t(topic), q, opts[4], a(index), why(correct explanation), wrong{idx:text}}
const MCQ = [
// ---------- CHEMISTRY REVIEW ----------
{id:"a1",t:"chem",q:"⁷⁹Br and ⁸¹Br are isotopes of bromine. They differ in their number of",
 opts:["protons","electrons","neutrons","valence shells"],a:2,
 why:"Isotopes are the same element (same 35 protons) with different neutron counts, so different mass. This is the exact example from the chemistry review slide.",
 wrong:{0:"Changing protons would make a different element.",1:"Changing electrons makes an ion, not an isotope.",3:"Both have the same electron arrangement."}},
{id:"a2",t:"chem",q:"A bromide ion (Br⁻) differs from a neutral bromine atom in that it has",
 opts:["one more proton","one more electron","one fewer neutron","one fewer electron"],a:1,
 why:"Ions form by gaining or losing electrons. Gaining an electron gives a negative charge (Br⁻: 35 protons, 36 electrons).",
 wrong:{0:"Proton count identifies the element and never changes in ion formation.",2:"Neutron changes make isotopes, not ions.",3:"Losing an electron would make a POSITIVE ion."}},
{id:"a3",t:"chem",q:"Which subatomic particle determines the identity of an element?",
 opts:["Neutron","Electron","Proton","Valence electron"],a:2,
 why:"The number of protons (atomic number) defines the element. Neutrons add mass; electrons determine charge and bonding.",
 wrong:{0:"Neutrons vary among isotopes of the same element.",1:"Electrons vary among ions of the same element.",3:"Valence electrons govern bonding behavior, not identity."}},
{id:"a4",t:"chem",q:"An atom's chemical bonding behavior depends primarily on its",
 opts:["number of neutrons","valence electrons (outer shell)","atomic mass","number of isotopes"],a:1,
 why:"Valence electrons are the ones available to be shared or transferred; they determine how many bonds an atom forms (C 4, N 3, O 2, H 1).",
 wrong:{0:"Neutrons affect mass only.",2:"Mass doesn't govern bonding.",3:"Isotopes don't change bonding behavior."}},
{id:"a5",t:"chem",q:"About 96% of living matter is made of which four elements?",
 opts:["C, H, O, P","C, H, O, N","C, N, S, P","H, O, Ca, K"],a:1,
 why:"CHON. Phosphorus, sulfur, calcium and potassium make up most of the remaining 4%.",
 wrong:{0:"Phosphorus is in the next tier, not the big four.",2:"Missing hydrogen and oxygen — the two most abundant.",3:"Ca and K are trace-level compared with C, H, O, N."}},
{id:"a6",t:"chem",q:"Electronegativity is best defined as",
 opts:["the number of electrons in an atom's outer shell","an atom's ability to attract shared electrons in a chemical bond","the charge of an ion","the energy released when a bond forms"],a:1,
 why:"Oxygen's high electronegativity pulls shared electrons toward it in the O–H bond, giving water its partial charges and polarity.",
 wrong:{0:"That's the valence electron count.",2:"That's ionic charge.",3:"That's bond energy."}},
{id:"a7",t:"chem",q:"In a NONPOLAR covalent bond, electrons are",
 opts:["transferred from one atom to another","shared unequally, creating partial charges","shared equally between atoms of similar electronegativity","not involved"],a:2,
 why:"Equal sharing (as in C–H or C–C) means no partial charges — the basis of nonpolar hydrocarbons and hydrophobic regions.",
 wrong:{0:"Transfer is ionic bonding.",1:"Unequal sharing is a POLAR covalent bond.",3:"All bonds involve electrons."}},
{id:"a8",t:"chem",q:"Table salt (NaCl) dissolves in water because",
 opts:["its covalent bonds are broken by heat","its ionic bond ionizes — Na⁺ and Cl⁻ separate and are surrounded by polar water molecules","water is nonpolar","NaCl forms hydrogen bonds"],a:1,
 why:"Ionic compounds are salts that dissociate in water; each ion is surrounded by oppositely charged ends of water molecules. Her note: ionic bonds are 'weak — ionize in water'.",
 wrong:{0:"NaCl has an ionic bond, not covalent.",2:"Water is polar — that's why it dissolves ions.",3:"Ions attract water's partial charges, but that isn't hydrogen bonding."}},

// ---------- WATER / POLARITY / BONDS ----------
{id:"w1",t:"water",q:"Water is a polar molecule primarily because",
 opts:["hydrogen bonds form within each water molecule","oxygen is more electronegative than hydrogen, so shared electrons sit closer to the oxygen","water contains both ionic and covalent bonds","the two hydrogens repel each other"],a:1,
 why:"Oxygen pulls the shared electrons toward itself, giving O a partial negative charge (δ−) and each H a partial positive charge (δ+). That uneven charge distribution is polarity.",
 wrong:{0:"Hydrogen bonds form BETWEEN water molecules, not within one. Within a molecule the O–H bonds are polar covalent.",2:"Water has only polar covalent bonds — no ionic bonds.",3:"Hydrogen repulsion has nothing to do with polarity; the cause is electronegativity difference."}},
{id:"w2",t:"water",q:"Which statement about hydrogen bonds is correct?",
 opts:["They are the strongest bonds in a water molecule","They are covalent bonds between H and O","They are weak attractions between a partially positive H on one molecule and a partially negative N, O, or F on another","They only occur in water"],a:2,
 why:"An H-bond is an intermolecular force (IMF): the δ+ hydrogen (bonded to N, O, or F) of one molecule is attracted to the δ− N, O, or F of another. Individually weak, collectively powerful.",
 wrong:{0:"Within a molecule the bonds are covalent and much stronger. H-bonds are between molecules.",1:"H-bonds are not covalent — no electrons are shared.",3:"H-bonds occur in DNA base pairing, protein secondary structure, and anywhere N–H or O–H groups are present."}},
{id:"w3",t:"water",q:"A water strider can walk on the surface of a pond. Which property of water best explains this?",
 opts:["Adhesion","High specific heat","Cohesion producing surface tension","Evaporative cooling"],a:2,
 why:"Cohesion — water molecules H-bonding to one another — makes the surface behave like a stretched film (surface tension) that supports the insect.",
 wrong:{0:"Adhesion is water sticking to OTHER polar substances, like xylem walls.",1:"Specific heat is about temperature change, not surface behavior.",3:"Evaporative cooling explains sweating, not surface support."}},
{id:"w4",t:"water",q:"Water moves up a plant's xylem against gravity. Which pair of properties is responsible?",
 opts:["Cohesion and adhesion","Surface tension and floating ice","High specific heat and evaporative cooling","Versatile solvent and adhesion"],a:0,
 why:"Adhesion sticks water to the xylem walls; cohesion pulls the rest of the water column along behind it. Together: capillary action.",
 wrong:{1:"Floating ice is irrelevant to transport in a tube.",2:"These are thermal properties, not transport properties.",3:"Solvent ability doesn't move water upward."}},
{id:"w5",t:"water",q:"A researcher heats 100 mL of water and 100 mL of ethanol with the same energy input. The ethanol's temperature rises faster. Which best explains the difference?",
 opts:["Ethanol molecules form stronger hydrogen bonds than water molecules","Water has a lower specific heat capacity than ethanol","Water's hydrogen bonds absorb more energy before its temperature increases","Ethanol has more cohesive properties than water"],a:2,
 why:"This is the exact question from the class slides. Water's extensive H-bonding means added energy first goes into breaking H-bonds before it can raise molecular motion (temperature). That's high specific heat.",
 wrong:{0:"Backwards: water H-bonds more extensively than ethanol.",1:"Backwards: water has a HIGHER specific heat, which is why it heats slowly.",3:"Backwards, and cohesion isn't the direct explanation for heating rate."}},
{id:"w6",t:"water",q:"Why does ice float on liquid water?",
 opts:["Ice contains fewer hydrogen bonds than liquid water","Hydrogen bonds in ice hold molecules in an open lattice, making solid water less dense than liquid","Ice is a nonpolar form of water","Dissolved gases in ice make it lighter"],a:1,
 why:"In ice, each water molecule is locked into 4 stable H-bonds forming a spaced-out crystal lattice, so molecules are farther apart than in liquid water. Water is densest at 4 °C.",
 wrong:{0:"Ice actually has MORE stable H-bonds than liquid water; that's what creates the open lattice.",2:"Water is polar in every state.",3:"Density of ice is about molecular spacing, not dissolved gas."}},
{id:"w7",t:"water",q:"Coastal cities like Santa Barbara stay cooler in summer than inland cities like Palm Springs. Which property of water is responsible?",
 opts:["Floating ice","High specific heat","Adhesion","Versatile solvent"],a:1,
 why:"The ocean absorbs huge amounts of heat with only a small temperature change (high specific heat), moderating the climate nearby.",
 wrong:{0:"No ice is involved.",2:"Adhesion concerns sticking to surfaces.",3:"Dissolving solutes doesn't moderate temperature."}},
{id:"w8",t:"water",q:"Which is the correct order of bond/interaction strength, strongest to weakest?",
 opts:["Hydrogen bond > ionic bond > covalent bond","Covalent bond > ionic bond > hydrogen bond","Ionic bond > hydrogen bond > covalent bond","Hydrogen bond > covalent bond > ionic bond"],a:1,
 why:"Covalent (shared electrons) are strongest and hold molecules together; ionic bonds fall apart (ionize) in water; hydrogen bonds are individually weak IMFs between molecules.",
 wrong:{0:"Reversed.",2:"Covalent is the strongest, not the weakest.",3:"Hydrogen bonds are the weakest of the three."}},
{id:"w9",t:"water",q:"In a covalent bond, electrons are ______; in an ionic bond, electrons are ______.",
 opts:["transferred; shared","shared; transferred","shared equally; shared unequally","lost; gained"],a:1,
 why:"Covalent = shared (equally in nonpolar, unequally in polar). Ionic = transferred, producing charged ions that attract (like Na⁺ and Cl⁻).",
 wrong:{0:"Reversed.",2:"That describes nonpolar vs polar COVALENT bonds, not covalent vs ionic.",3:"Only ionic bonding involves losing/gaining."}},
{id:"w10",t:"water",q:"A solution has a high concentration of H⁺ ions. It is",
 opts:["basic, with a high pH","acidic, with a low pH","neutral","acidic, with a high pH"],a:1,
 why:"pH measures H⁺ concentration inversely: more H⁺ = lower pH = acidic. Acids donate H⁺; bases take up H⁺.",
 wrong:{0:"High H⁺ is acidic and LOW pH.",2:"Neutral is pH 7 with balanced H⁺ and OH⁻.",3:"High H⁺ means low pH, not high."}},
{id:"w11",t:"water",q:"Living cells contain buffers. The function of a buffer is to",
 opts:["increase the pH of the cytoplasm","supply H⁺ ions for chemical reactions","resist changes in pH","dissolve nonpolar molecules"],a:2,
 why:"Living things tolerate only a narrow pH range. Buffers absorb or release H⁺ to prevent large pH swings.",
 wrong:{0:"Buffers don't push pH in one direction; they hold it steady.",1:"Buffers can release H⁺ but their job is stabilization, not supply.",3:"That's unrelated to pH."}},
{id:"w12",t:"water",q:"Which molecule would you expect to be hydrophobic?",
 opts:["A molecule with many –OH groups","A long hydrocarbon chain of only C and H","A molecule with an –NH₂ group","A molecule with a –PO₄ group"],a:1,
 why:"Nonpolar = hydrophobic. C and H share electrons nearly equally, so hydrocarbons have no polar regions. Remember: N and O are the clues for polar.",
 wrong:{0:"Hydroxyl groups are polar → hydrophilic.",2:"Amino groups are polar and charged → hydrophilic.",3:"Phosphate groups are polar and charged → hydrophilic."}},

// ---------- CARBON & FUNCTIONAL GROUPS ----------
{id:"g1",t:"groups",q:"Carbon is the backbone of all macromolecules mainly because it",
 opts:["is the most abundant element on Earth","can form four stable covalent bonds in many shapes","forms ionic bonds easily","is highly electronegative"],a:1,
 why:"Four valence positions let carbon build chains, branches, rings, and single/double/triple bonds — endless variety.",
 wrong:{0:"Oxygen is more abundant in living matter; abundance isn't the reason.",2:"Carbon almost always bonds covalently.",3:"Carbon has moderate electronegativity — that's why C–H bonds are nonpolar."}},
{id:"g2",t:"groups",q:"Two molecules have the identical formula C₆H₁₂O₆ but different structures and functions. They are",
 opts:["isotopes","ions","isomers","polymers"],a:2,
 why:"Isomers share a formula but differ in arrangement — and shape determines function. Thalidomide's two mirror-image isomers (one a sedative, one causing birth defects) were the class example.",
 wrong:{0:"Isotopes are atoms of the same element with different neutron counts.",1:"Ions are charged atoms or molecules.",3:"Polymers are long chains of monomers."}},
{id:"g3",t:"groups",q:"Which functional group is nonpolar?",
 opts:["Hydroxyl (–OH)","Methyl (–CH₃)","Carboxyl (–COOH)","Amino (–NH₂)"],a:1,
 why:"Methyl is just carbon and hydrogen, which share electrons nearly equally. Every other group listed contains O or N → polar.",
 wrong:{0:"Hydroxyl contains O → polar.",2:"Carboxyl is polar, negatively charged, and acidic.",3:"Amino is polar, positively charged, and basic."}},
{id:"g4",t:"groups",q:"Which functional group acts as a base by picking up an H⁺ from solution?",
 opts:["Carboxyl","Phosphate","Amino","Hydroxyl"],a:2,
 why:"–NH₂ accepts a proton to become –NH₃⁺ — that's a base, and it becomes positively charged.",
 wrong:{0:"Carboxyl DONATES H⁺ (–COOH → –COO⁻): acidic.",1:"Phosphate donates H⁺: acidic.",3:"Hydroxyl is polar but neither acidic nor basic in this context."}},
{id:"g5",t:"groups",q:"Which two functional groups are both polar, negatively charged, and acidic?",
 opts:["Hydroxyl and carbonyl","Amino and sulfhydryl","Carboxyl and phosphate","Methyl and carboxyl"],a:2,
 why:"Both –COOH and –PO₄ give up H⁺ in water, leaving a negative charge. Carboxyl is on fatty acids and amino acids; phosphate is on nucleotides, phospholipids, and ATP.",
 wrong:{0:"Both polar, but neither is charged or acidic.",1:"Amino is basic and positive; sulfhydryl is neither.",3:"Methyl is nonpolar."}},
{id:"g6",t:"groups",q:"A carbonyl group (C=O) located at the END of a carbon chain is a(n)",
 opts:["ketone","aldehyde","carboxyl","ester"],a:1,
 why:"Aldehyde = at the end. Ketone = kaptured in the middle.",
 wrong:{0:"A ketone's C=O is in the middle of the chain.",2:"A carboxyl is C=O plus –OH on the same carbon (–COOH).",3:"An ester is the bond linking glycerol to a fatty acid."}},
{id:"g7",t:"groups",q:"The sulfhydryl group (–SH) is important in proteins because",
 opts:["it forms the peptide bond","it makes the protein acidic","two of them can form a covalent disulfide bridge that stabilizes tertiary structure","it is the most polar functional group"],a:2,
 why:"Cysteine's –SH groups pair up as S–S disulfide bridges — the only covalent interaction stabilizing 3° and 4° structure, making them especially strong.",
 wrong:{0:"Peptide bonds form between carboxyl and amino groups.",1:"Sulfhydryl isn't acidic in this context.",3:"It's weakly polar at best."}},
{id:"g8",t:"groups",q:"Why must you recognize a carboxyl group as ONE group rather than 'a carbonyl plus a hydroxyl'?",
 opts:["Because the two never appear on the same carbon","Because the combination has new properties (charged, acidic) not present in either part alone — an emergent property","Because carboxyl is nonpolar while its parts are polar","Because the hydroxyl leaves during the reaction"],a:1,
 why:"Neither a carbonyl nor a hydroxyl is acidic or charged on its own, but together as –COOH they release H⁺. New properties at a higher level of organization = emergent property.",
 wrong:{0:"They do appear on the same carbon — that's exactly what a carboxyl is.",2:"Carboxyl is polar.",3:"That describes dehydration synthesis, not why carboxyl is a distinct group."}},
{id:"g9",t:"groups",q:"In a skeletal (zig-zag) line drawing of a hydrocarbon with 7 corners/ends and no other atoms shown, how many carbons and hydrogens are there (assume one double bond)?",
 opts:["7 C, 16 H","7 C, 14 H","6 C, 14 H","7 C, 18 H"],a:1,
 why:"Every corner or end is a carbon → 7 C. Fill each carbon to 4 bonds with H: a 7-carbon chain with one double bond has 14 H (C₇H₁₄). With no double bond it would be C₇H₁₆ — the exact example in the class notes.",
 wrong:{0:"C₇H₁₆ is correct only if there is no double bond.",2:"Count corners AND ends — there are 7 carbons.",3:"Too many hydrogens for 7 carbons."}},
{id:"g10",t:"groups",q:"The phosphate group is involved in which bond?",
 opts:["Peptide bond","Glycosidic linkage","Ester linkage","Phosphodiester bond"],a:3,
 why:"Phosphodiester bonds link nucleotides in DNA and RNA via the phosphate group. Hydrolysis of phosphate bonds also releases a lot of energy (ATP).",
 wrong:{0:"Peptide bonds join amino acids (carboxyl + amino).",1:"Glycosidic linkages join sugars.",2:"Ester linkages join glycerol and fatty acids."}},

// ---------- BUILD & BREAK ----------
{id:"b1",t:"build",q:"Dehydration synthesis",
 opts:["adds a water molecule to break a polymer into monomers","removes a water molecule to join two monomers with a covalent bond","breaks hydrogen bonds using heat","converts a polar molecule into a nonpolar one"],a:1,
 why:"An –H from one monomer and an –OH from the other leave as H₂O; a covalent bond forms where they were. Also called a condensation reaction.",
 wrong:{0:"That is hydrolysis, the reverse.",2:"Dehydration synthesis forms covalent bonds; it isn't about H-bonds.",3:"Polarity isn't the point of the reaction."}},
{id:"b2",t:"build",q:"Digesting a disaccharide into two monosaccharides requires",
 opts:["dehydration synthesis and the removal of one water","hydrolysis and the addition of one water","condensation and an enzyme that adds a phosphate","oxidation"],a:1,
 why:"Hydro-lysis = water splits. Adding H₂O breaks the glycosidic bond, restoring the –OH and –H on each monomer.",
 wrong:{0:"Dehydration synthesis BUILDS; it doesn't digest.",2:"No phosphate is involved in breaking a sugar bond.",3:"Oxidation is not the reaction that splits polymers."}},
{id:"b3",t:"build",q:"Glucose (C₆H₁₂O₆) and fructose (C₆H₁₂O₆) join to form sucrose. Sucrose's formula is",
 opts:["C₁₂H₂₄O₁₂","C₁₂H₂₂O₁₁","C₁₂H₂₀O₁₀","C₆H₁₂O₆"],a:1,
 why:"Add the two monomers and subtract one water: C₁₂H₂₄O₁₂ − H₂O = C₁₂H₂₂O₁₁.",
 wrong:{0:"You forgot to subtract the water lost in dehydration synthesis.",2:"That subtracts two waters — only one bond forms.",3:"That's the formula of a single hexose."}},
{id:"b4",t:"build",q:"How many water molecules are released when a triglyceride forms from glycerol and three fatty acids?",
 opts:["1","2","3","6"],a:2,
 why:"Each fatty acid attaches to glycerol by one ester bond via dehydration synthesis; three bonds → three waters.",
 wrong:{0:"One water per bond, and there are three bonds.",1:"A phospholipid with 2 fatty acids would release 2 (plus one for the phosphate), but a triglyceride has 3.",3:"Only one water per ester bond."}},
{id:"b5",t:"build",q:"Match the bond to the polymer: the bond between two amino acids is a ______ bond; between two nucleotides, a ______ bond.",
 opts:["glycosidic; ester","peptide; phosphodiester","ester; peptide","phosphodiester; glycosidic"],a:1,
 why:"Peptide (proteins), phosphodiester (nucleic acids), glycosidic (carbs), ester (lipids). Your teacher asks for the SPECIFIC name.",
 wrong:{0:"Glycosidic is sugars; ester is lipids.",2:"Reversed roles, and ester is for lipids.",3:"Reversed."}},
{id:"b6",t:"build",q:"Which correctly pairs a polymer with its monomer?",
 opts:["Polysaccharide — amino acid","Polypeptide — nucleotide","Nucleic acid — monosaccharide","Polypeptide — amino acid"],a:3,
 why:"Polysaccharide ← monosaccharide; polypeptide ← amino acid; nucleic acid ← nucleotide. Lipids are the odd one out with no true monomer.",
 wrong:{0:"Polysaccharides are made of monosaccharides.",1:"Polypeptides are made of amino acids.",2:"Nucleic acids are made of nucleotides."}},
{id:"b7",t:"build",q:"Which functional group is most often lost as part of the water molecule in dehydration synthesis?",
 opts:["Methyl","Hydroxyl","Carbonyl","Sulfhydryl"],a:1,
 why:"An –OH from one monomer combines with an –H from the other to form H₂O. Hydroxyl groups on sugars, and the –OH of carboxyl groups, are the usual participants.",
 wrong:{0:"Methyl doesn't participate in dehydration synthesis.",2:"Carbonyl stays put.",3:"Sulfhydryl forms disulfide bridges, not water."}},
{id:"b8",t:"build",q:"Which is true of ALL the bonds that link monomers into polymers (glycosidic, ester, peptide, phosphodiester)?",
 opts:["They are hydrogen bonds","They are ionic bonds","They are covalent bonds formed by dehydration synthesis","They are broken by heat alone"],a:2,
 why:"All four are covalent bonds built by removing water. Breaking them requires hydrolysis, typically with an enzyme — not just heat.",
 wrong:{0:"H-bonds are far too weak to hold polymers together.",1:"Ionic bonds fall apart in water; polymers don't.",3:"Heat disrupts weak interactions, not covalent backbone bonds."}},

// ---------- CARBS ----------
{id:"c1",t:"carbs",q:"The general formula for a carbohydrate is",
 opts:["(CH₂O)ₙ","CₙH₂ₙOₙ₊₁","(CHO)ₙ","C₂ₙHₙOₙ"],a:0,
 why:"Carbo-hydrate: carbon plus water. H:O is always 2:1, e.g. C₆H₁₂O₆.",
 wrong:{1:"Oxygen equals carbon in a simple sugar.",2:"H must be twice O.",3:"Hydrogen, not carbon, is doubled."}},
{id:"c2",t:"carbs",q:"Ribose is a pentose. Its formula is",
 opts:["C₆H₁₂O₆","C₅H₁₀O₅","C₃H₆O₃","C₅H₁₂O₆"],a:1,
 why:"Pent- = 5 carbons; apply (CH₂O)₅.",
 wrong:{0:"That's a hexose (glucose, fructose, galactose).",2:"That's a triose.",3:"Breaks the 2:1 H:O ratio."}},
{id:"c3",t:"carbs",q:"Lactose is a disaccharide made of",
 opts:["glucose + glucose","glucose + fructose","glucose + galactose","fructose + galactose"],a:2,
 why:"Lactose (milk sugar) = glucose + galactose. Sucrose = glucose + fructose. Maltose = glucose + glucose.",
 wrong:{0:"That's maltose.",1:"That's sucrose (table sugar).",3:"Not a common disaccharide."}},
{id:"c4",t:"carbs",q:"Which polysaccharide is used for energy STORAGE in ANIMALS?",
 opts:["Starch","Cellulose","Chitin","Glycogen"],a:3,
 why:"Glycogen is stored in liver and muscle. Starch is plant storage; cellulose is plant structure; chitin is animal/fungal structure.",
 wrong:{0:"Starch is the plant storage polysaccharide.",1:"Cellulose is structural (plant cell walls).",2:"Chitin is structural (insect exoskeletons, fungal cell walls)."}},
{id:"c5",t:"carbs",q:"Starch and cellulose are both polymers of glucose, yet humans can digest only starch. Why?",
 opts:["Cellulose is made of fructose, not glucose","Starch has alpha linkages our enzymes fit; cellulose has beta linkages we lack enzymes for","Cellulose is too large to be digested","Starch is polar and cellulose is nonpolar"],a:1,
 why:"Structure → function. The different linkage geometry (α vs β) means our enzymes can't bind cellulose. Herbivores rely on gut bacteria to do it.",
 wrong:{0:"Both are pure glucose polymers.",2:"Size isn't the barrier — starch is huge too.",3:"Both are polar carbohydrates."}},
{id:"c6",t:"carbs",q:"Glycogen is more highly branched than starch. What functional advantage does this give?",
 opts:["It stores more energy per gram","More free ends let enzymes hydrolyze it faster, releasing glucose quickly","It makes glycogen insoluble","It allows glycogen to form cell walls"],a:1,
 why:"Enzymes remove glucose from the ends of chains. More branches = more ends = faster release. Animals need quick energy on demand.",
 wrong:{0:"Energy per glucose is the same.",2:"Branching doesn't govern solubility that way.",3:"Glycogen is a storage molecule, not structural."}},
{id:"c7",t:"carbs",q:"Carbohydrates are always polar because",
 opts:["they contain nitrogen","they contain many hydroxyl (–OH) groups","they are very large molecules","they contain phosphate"],a:1,
 why:"The many –OH groups on every sugar ring contain oxygen and are polar, so sugars dissolve readily in water.",
 wrong:{0:"Carbohydrates contain only C, H, O.",2:"Size doesn't determine polarity.",3:"Sugars don't contain phosphate (nucleotides do)."}},
{id:"c8",t:"carbs",q:"Deoxyribose differs from ribose in that deoxyribose",
 opts:["has an extra oxygen on the 2′ carbon","is missing an oxygen on the 2′ carbon","is a hexose","contains nitrogen"],a:1,
 why:"De-oxy = missing oxygen. The 2′ carbon has –H instead of –OH. The class slide asked: 'Which carbon is missing an O in deoxyribose?' → 2′.",
 wrong:{0:"Reversed — it has one FEWER oxygen.",2:"Both are pentoses (5 C).",3:"Sugars don't contain nitrogen."}},
{id:"c9",t:"carbs",q:"A cow can digest grass (cellulose) because",
 opts:["cows produce cellulase in their stomach lining","bacteria living in the cow's digestive system break the beta linkages","cellulose is converted to starch when chewed","cows have alpha-linkage enzymes"],a:1,
 why:"Animals don't make the enzyme for beta linkages; symbiotic gut bacteria do.",
 wrong:{0:"The cow itself doesn't produce the enzyme.",2:"Chewing doesn't change the chemical linkage.",3:"Alpha enzymes don't fit beta linkages."}},

// ---------- LIPIDS ----------
{id:"l1",t:"lipids",q:"A triglyceride consists of",
 opts:["three glycerols and one fatty acid","one glycerol and three fatty acids","two fatty acids, glycerol and a phosphate","four fused carbon rings"],a:1,
 why:"Glycerol (3 carbons, each with –OH) + 3 fatty acids, joined by 3 ester bonds.",
 wrong:{0:"Reversed.",2:"That's a phospholipid.",3:"That's a steroid."}},
{id:"l2",t:"lipids",q:"Compared to saturated fatty acids, unsaturated fatty acids",
 opts:["have only single C–C bonds and are solid at room temperature","have one or more double bonds, are kinked, and are liquid at room temperature","contain more hydrogen atoms","are found mainly in animal fats"],a:1,
 why:"Double bonds put kinks in the chain so molecules can't pack tightly → liquid (plant oils). Saturated = all single bonds, straight, solid (butter).",
 wrong:{0:"That describes SATURATED fatty acids.",2:"Unsaturated chains have FEWER hydrogens (not saturated with H).",3:"Animal fats are mostly saturated; unsaturated are typical of plants."}},
{id:"l3",t:"lipids",q:"Phospholipids are described as amphipathic. This means",
 opts:["they are entirely nonpolar","they have both a polar (hydrophilic) region and a nonpolar (hydrophobic) region","they are soluble in water","they contain two phosphate groups"],a:1,
 why:"Polar phosphate head + nonpolar fatty-acid tails. This dual nature drives bilayer formation.",
 wrong:{0:"The head is polar.",2:"Only the head interacts with water; the tails avoid it.",3:"One phosphate, two fatty acids."}},
{id:"l4",t:"lipids",q:"In a cell membrane, phospholipids form a bilayer in which",
 opts:["hydrophobic tails face the watery environment on both sides","hydrophilic heads face outward toward water and hydrophobic tails point inward","heads and tails alternate randomly","all phosphate groups cluster in the center"],a:1,
 why:"Like attracts like: polar heads toward polar water (inside and outside the cell); nonpolar tails hide together in the middle.",
 wrong:{0:"Nonpolar tails avoid water.",2:"The arrangement is highly ordered, not random.",3:"Phosphates are polar and face the water, not the center."}},
{id:"l5",t:"lipids",q:"All steroids share",
 opts:["a glycerol backbone","a long hydrocarbon tail with a carboxyl end","four fused carbon rings","a phosphate group"],a:2,
 why:"Four fused rings + varying functional groups. Changing the functional groups changes the function (cholesterol, cortisol, estrogen, testosterone).",
 wrong:{0:"Glycerol is for fats and phospholipids.",1:"That's a fatty acid.",3:"Steroids have no phosphate."}},
{id:"l6",t:"lipids",q:"The bond linking a fatty acid to glycerol is a(n)",
 opts:["glycosidic linkage","peptide bond","ester linkage","phosphodiester bond"],a:2,
 why:"The carboxyl of the fatty acid reacts with a hydroxyl on glycerol → ester bond (R–C(=O)–O–R′) + water.",
 wrong:{0:"Glycosidic joins sugars.",1:"Peptide joins amino acids.",3:"Phosphodiester joins nucleotides."}},
{id:"l7",t:"lipids",q:"Lipids do not dissolve in water because",
 opts:["they are too large","they are mostly nonpolar hydrocarbon and have very little oxygen","they are charged","they contain nitrogen"],a:1,
 why:"Their H:O ratio is far from 2:1 — mostly C–H bonds, which are nonpolar. Nonpolar doesn't dissolve in polar.",
 wrong:{0:"Size isn't the reason; huge polysaccharides are polar and water-soluble.",2:"Lipids are uncharged (except phospholipid heads).",3:"Lipids contain C, H, O (and P in phospholipids), not N."}},
{id:"l8",t:"lipids",q:"Which function is NOT typically attributed to lipids?",
 opts:["Long-term energy storage","Insulation and cushioning organs","Storing genetic information","Chemical signaling (hormones)"],a:2,
 why:"Genetic information is the job of nucleic acids. Lipids store energy, insulate, cushion, build membranes, and act as steroid hormones.",
 wrong:{0:"Fats store energy long-term (more bonds than carbs).",1:"Fat insulates and cushions.",3:"Steroid hormones like estrogen and testosterone are lipids."}},
{id:"l9",t:"lipids",q:"Which change would make a fat more likely to be liquid at room temperature?",
 opts:["Replacing unsaturated fatty acids with saturated ones","Adding more C=C double bonds to the fatty acid chains","Lengthening the saturated fatty acid chains","Removing the glycerol"],a:1,
 why:"More double bonds → more kinks → looser packing → lower melting point → liquid.",
 wrong:{0:"Saturated fats pack tightly and are solid.",2:"Longer saturated chains are MORE solid.",3:"Removing glycerol would mean it isn't a fat."}},

// ---------- PROTEINS ----------
{id:"p1",t:"proteins",q:"All 20 amino acids share the same",
 opts:["R-group","central carbon bonded to an amino group, a carboxyl group, and a hydrogen","number of sulfur atoms","polarity"],a:1,
 why:"Same backbone; only the R-group differs. The R-group's chemistry (polar, nonpolar, charged) determines how the protein folds.",
 wrong:{0:"The R-group is the ONE thing that differs.",2:"Only cysteine and methionine contain sulfur.",3:"Polarity varies with the R-group."}},
{id:"p2",t:"proteins",q:"A peptide bond forms between the ______ of one amino acid and the ______ of the next.",
 opts:["R-group; R-group","carboxyl group; amino group","hydroxyl group; methyl group","amino group; phosphate group"],a:1,
 why:"Dehydration synthesis: the carboxyl's –OH and the amino's –H leave as water, forming a covalent C–N bond. Hence chains run amino (N) terminus → carboxyl (C) terminus.",
 wrong:{0:"R-groups interact in 3° structure but don't form the backbone bond.",2:"No hydroxyl–methyl bond exists here.",3:"Amino acids have no phosphate."}},
{id:"p3",t:"proteins",q:"Primary (1°) protein structure is",
 opts:["the folding into alpha helices and beta sheets","the sequence of amino acids, held by covalent peptide bonds","the overall 3-D shape from R-group interactions","the assembly of multiple polypeptides"],a:1,
 why:"Order of amino acids, determined by DNA, held by peptide bonds. It ultimately determines how the protein folds.",
 wrong:{0:"That's secondary.",2:"That's tertiary.",3:"That's quaternary."}},
{id:"p4",t:"proteins",q:"Secondary (2°) structure (α-helix, β-pleated sheet) is held together by",
 opts:["hydrogen bonds between R-groups","hydrogen bonds between backbone C=O and N–H groups","disulfide bridges","peptide bonds"],a:1,
 why:"Backbone-to-backbone H-bonds; the R-groups are NOT involved. This is the most-tested distinction in the POGIL.",
 wrong:{0:"R-group interactions are 3° (and 4°).",2:"Disulfide bridges are 3°/4°.",3:"Peptide bonds are 1°."}},
{id:"p5",t:"proteins",q:"Tertiary (3°) structure results from interactions between",
 opts:["backbone atoms only","R-groups of amino acids within one polypeptide","separate polypeptide chains","nucleotides"],a:1,
 why:"H-bonds, ionic bonds, hydrophobic interactions, and disulfide bridges among R-groups fold one chain into its overall 3-D shape.",
 wrong:{0:"Backbone-only is secondary.",2:"Interactions between chains is quaternary.",3:"Proteins aren't made of nucleotides."}},
{id:"p6",t:"proteins",q:"Hemoglobin consists of four polypeptide subunits. This is an example of",
 opts:["primary structure","secondary structure","tertiary structure","quaternary structure"],a:3,
 why:"Two or more polypeptides assembled into one functional protein = 4°. Not all proteins have it.",
 wrong:{0:"1° is sequence.",1:"2° is local folding.",2:"3° is the shape of ONE chain."}},
{id:"p7",t:"proteins",q:"Which interaction stabilizing tertiary structure is covalent and therefore strongest?",
 opts:["Hydrogen bond","Ionic bond","Hydrophobic interaction","Disulfide bridge"],a:3,
 why:"S–S bonds between two cysteine –SH groups are covalent; the others are weaker IMFs.",
 wrong:{0:"H-bonds are weak IMFs.",1:"Ionic bonds are weaker than covalent and fall apart in water.",2:"Hydrophobic interactions are weak clustering, not bonds."}},
{id:"p8",t:"proteins",q:"Which type of R-group would be found clustered in the INTERIOR of a water-soluble protein?",
 opts:["Polar","Charged (acidic)","Nonpolar","Charged (basic)"],a:2,
 why:"Nonpolar R-groups avoid water and pack together inside — hydrophobic interactions. Polar and charged R-groups face the watery outside.",
 wrong:{0:"Polar R-groups face water.",1:"Charged groups interact with water and form ionic bonds on the surface.",3:"Same — charged groups stay near water."}},
{id:"p9",t:"proteins",q:"An egg white turns solid when cooked because heat",
 opts:["breaks the peptide bonds of albumin","disrupts the weak interactions holding 2°, 3° and 4° structure, denaturing albumin","adds water to the protein","converts albumin into a carbohydrate"],a:1,
 why:"Denaturing = unfolding. Heat breaks H-bonds, ionic bonds and hydrophobic interactions; the unfolded proteins tangle together. Structural change → functional change.",
 wrong:{0:"Peptide bonds are covalent and survive cooking; 1° structure is intact.",2:"Cooking doesn't hydrolyze the protein.",3:"Impossible — the elements don't match."}},
{id:"p10",t:"proteins",q:"After a protein is denatured by heat, which level of structure remains intact?",
 opts:["Primary","Secondary","Tertiary","Quaternary"],a:0,
 why:"The covalent peptide bonds need an enzyme (hydrolysis) to break. Heat only disrupts the weak interactions of 2°, 3°, 4°.",
 wrong:{1:"2° H-bonds break under heat.",2:"3° interactions break under heat.",3:"4° interactions break under heat."}},
{id:"p11",t:"proteins",q:"Chemical hair straightening works by breaking and re-forming which interactions?",
 opts:["Peptide bonds","Disulfide bonds between cysteines (3°/4° structure)","Hydrogen bonds in the backbone only","Glycosidic linkages"],a:1,
 why:"One chemical breaks the S–S bridges that give keratin its curl; a second re-forms them in the straight position. It grows out because new hair is made and the chemicals wear off.",
 wrong:{0:"Breaking peptide bonds would destroy the hair.",2:"The permanent effect comes from covalent disulfide bonds.",3:"Hair is protein, not carbohydrate."}},
{id:"p12",t:"proteins",q:"A mutation replaces a polar amino acid with a nonpolar one. Which levels of structure are MOST LIKELY affected?",
 opts:["Only primary","Primary for certain; tertiary and quaternary most likely, since R-group interactions stabilize them","Only quaternary","None — one amino acid can't change a protein"],a:1,
 why:"1° changes by definition. 2° may or may not (backbone-based; depends on location). 3°/4° depend on R-group chemistry, so swapping polar → nonpolar likely alters the fold and function.",
 wrong:{0:"The R-group change ripples into folding.",2:"1° is definitely changed.",3:"Sickle-cell disease results from a single amino acid change."}},
{id:"p13",t:"proteins",q:"An enzyme moved to a solution with a very different pH loses activity because",
 opts:["its peptide bonds hydrolyze","the pH change disrupts H-bonds and ionic bonds between R-groups, changing the enzyme's shape","its amino acids are converted to nucleotides","the enzyme dissolves"],a:1,
 why:"Changing H⁺ concentration alters the charges on acidic and basic R-groups, breaking ionic bonds and H-bonds → denaturing → loss of function.",
 wrong:{0:"pH alone doesn't break covalent peptide bonds.",2:"Impossible.",3:"Dissolving isn't the mechanism."}},

// ---------- NUCLEIC ACIDS ----------
{id:"n1",t:"nucleic",q:"The three components of a nucleotide are",
 opts:["a phosphate, a 6-carbon sugar, and an amino acid","a phosphate, a 5-carbon sugar, and a nitrogenous base","a glycerol, a fatty acid, and a base","a nitrogenous base, an amino group, and a carboxyl group"],a:1,
 why:"Phosphate + pentose (ribose or deoxyribose) + nitrogenous base (A, T/U, C, G).",
 wrong:{0:"The sugar is a pentose and there's no amino acid.",2:"Those are lipid parts.",3:"Those are amino acid parts."}},
{id:"n2",t:"nucleic",q:"Nucleotides in a strand are joined by",
 opts:["hydrogen bonds between bases","phosphodiester bonds between the phosphate and the sugar of the next nucleotide","peptide bonds","glycosidic linkages"],a:1,
 why:"Covalent phosphodiester bonds form the sugar-phosphate backbone. Hydrogen bonds hold the two STRANDS together, not the nucleotides within a strand.",
 wrong:{0:"H-bonds pair bases ACROSS strands.",2:"Peptide bonds are for proteins.",3:"Glycosidic linkages are for sugars."}},
{id:"n3",t:"nucleic",q:"Which are the purines?",
 opts:["Cytosine and thymine","Adenine and guanine","Adenine and thymine","Uracil and cytosine"],a:1,
 why:"Ag = pure silver: Adenine and Guanine are purines (two rings). Don't get CUT on the pyramid: C, U, T are pyrimidines (one ring).",
 wrong:{0:"Both are pyrimidines.",2:"Adenine is a purine, thymine a pyrimidine — they PAIR.",3:"Both are pyrimidines."}},
{id:"n4",t:"nucleic",q:"In DNA, adenine pairs with ______ via ______ hydrogen bonds; cytosine pairs with ______ via ______ hydrogen bonds.",
 opts:["thymine; 3; guanine; 2","guanine; 2; thymine; 3","thymine; 2; guanine; 3","uracil; 2; guanine; 3"],a:2,
 why:"A=T with 2 H-bonds; C≡G with 3. A purine always pairs with a pyrimidine so the helix stays a constant width.",
 wrong:{0:"Numbers reversed.",1:"Partners wrong: A pairs with T, C with G.",3:"Uracil is only in RNA."}},
{id:"n5",t:"nucleic",q:"Which is a structural difference between DNA and RNA?",
 opts:["DNA contains uracil; RNA contains thymine","DNA contains ribose; RNA contains deoxyribose","DNA is usually double-stranded; RNA is usually single-stranded","DNA has phosphodiester bonds; RNA has peptide bonds"],a:2,
 why:"Three differences: sugar (deoxyribose vs ribose), base (thymine vs uracil), strands (double vs single).",
 wrong:{0:"Reversed — DNA has thymine, RNA has uracil.",1:"Reversed — DNA has DEOXYribose.",3:"Both use phosphodiester bonds."}},
{id:"n6",t:"nucleic",q:"The two strands of a DNA double helix are described as antiparallel because",
 opts:["they are held by ionic bonds","they run in opposite 5′→3′ directions","one is DNA and one is RNA","they twist in opposite directions"],a:1,
 why:"Each strand has a 5′ phosphate end and a 3′ hydroxyl end; the partner strand runs the other way.",
 wrong:{0:"Strands are held by H-bonds between bases.",2:"Both are DNA.",3:"They twist together as one helix."}},
{id:"n7",t:"nucleic",q:"Given the DNA strand 5′-ACTGGCTAC-3′, the complementary strand is",
 opts:["TGACCGATG","ACTGGCTAC","UGACCGAUG","CATCGGTCA"],a:0,
 why:"A↔T, C↔G: A-C-T-G-G-C-T-A-C → T-G-A-C-C-G-A-T-G. This is the exact practice strand from the class slide.",
 wrong:{1:"That's the same strand, not its complement.",2:"Uracil is RNA — this is DNA.",3:"That's the complement written backwards from the other end."}},
{id:"n8",t:"nucleic",q:"Why is it important that the two DNA strands are held together by hydrogen bonds rather than covalent bonds?",
 opts:["Hydrogen bonds make DNA more stable than proteins","The strands can be 'unzipped' to access the bases for replication and transcription","Hydrogen bonds store more energy","Covalent bonds cannot form between nitrogen bases"],a:1,
 why:"Weak bonds are a feature: the cell can separate the strands without breaking the covalent backbone, then let them re-pair.",
 wrong:{0:"Weak bonds are less stable, which is the point.",2:"H-bonds store very little energy.",3:"It's not about impossibility — weak pairing is functionally necessary."}},
{id:"n9",t:"nucleic",q:"During DNA or RNA synthesis, new nucleotides are added to the",
 opts:["5′ phosphate end","3′ hydroxyl end","nitrogenous base","middle of the strand"],a:1,
 why:"Growth is 5′→3′: each incoming nucleotide's phosphate bonds to the free 3′ –OH of the growing strand.",
 wrong:{0:"The 5′ end carries the phosphate that started the strand.",2:"Bases pair; they don't extend the backbone.",3:"Strands grow from an end."}},
{id:"n10",t:"nucleic",q:"The flow of genetic information DNA → RNA → protein is called the central dogma. DNA → RNA is ______ and RNA → protein is ______.",
 opts:["translation; transcription","transcription; translation","replication; transcription","expression; replication"],a:1,
 why:"Transcription copies DNA into RNA (same nucleic-acid 'language'); translation converts RNA into amino-acid 'language'. Together: gene expression.",
 wrong:{0:"Reversed.",2:"Replication is DNA → DNA.",3:"Expression is the whole process; replication is DNA → DNA."}},
{id:"n11",t:"nucleic",q:"Nucleic acids are composed of which elements?",
 opts:["C, H, O","C, H, O, N","C, H, O, N, P","C, H, O, N, S"],a:2,
 why:"CHONP — the phosphate adds P. Proteins are CHON (+S in some R-groups); carbs and lipids are CHO.",
 wrong:{0:"That's carbohydrates and lipids.",1:"Missing the phosphorus of the phosphate group.",3:"Sulfur is in some proteins, not nucleic acids."}},

// ---------- FRQ SKILLS & DATA ----------
{id:"f1",t:"frq",q:"An FRQ part begins with the verb 'Identify.' The best response is",
 opts:["a paragraph explaining the mechanism","a short, specific answer naming the thing — no explanation needed","a restatement of the prompt followed by the answer","a labeled diagram"],a:1,
 why:"Identify = tell what it is. Short and quick. Extra explanation earns nothing and costs time. (Diagrams alone never earn credit.)",
 wrong:{0:"Save explanation for 'Explain' and 'Justify'.",2:"Restating the prompt earns zero.",3:"A diagram alone does not receive credit."}},
{id:"f2",t:"frq",q:"An FRQ asks you to 'Describe' a structure. You should",
 opts:["give relevant characteristics without explaining how or why","explain the mechanism in detail","predict what will happen","justify with data"],a:0,
 why:"Describe = characteristics, shorter answer. Explain (how/why) is the longer one.",
 wrong:{1:"That's 'Explain'.",2:"That's 'Predict'.",3:"That's 'Justify'."}},
{id:"f3",t:"frq",q:"You are asked to 'Justify' a claim using data from a table. A complete answer must",
 opts:["restate the claim","cite the specific data AND explain how or why that data supports the claim","list every value in the table","give your opinion"],a:1,
 why:"Two moves: point to the evidence, then connect it to the claim with reasoning. Longer answer.",
 wrong:{0:"Restating earns nothing.",2:"Cite the relevant values, not all of them.",3:"Justification is evidence-based, not opinion."}},
{id:"f4",t:"frq",q:"A data set compares trichome density of three separate plant populations. To 'Construct' a graph you should draw a",
 opts:["line graph, because there are three data points","bar graph, because the populations are discontinuous categories","pie chart","scatter plot with a trend line"],a:1,
 why:"Discontinuous (categorical) data → bar graph. Continuous data (time, temperature) → line graph.",
 wrong:{0:"Line graphs imply the x-axis is continuous.",2:"Pie charts show parts of a whole, not comparisons of means.",3:"No continuous x-variable to trend against."}},
{id:"f5",t:"frq",q:"A population's mean trichome density is 11 trichomes/cm² with SEM = 1. The 95% confidence interval error bars should span",
 opts:["10 to 12","9 to 13","11 to 13","8 to 14"],a:1,
 why:"95% CI ≈ mean ± 2 SEM = 11 ± 2 → 9 to 13. Calculate on scratch paper before drawing so the bars fit the grid.",
 wrong:{0:"That's ± 1 SEM.",2:"Bars extend both directions from the mean.",3:"That's ± 3 SEM."}},
{id:"f6",t:"frq",q:"On a 'Construct a graph' FRQ, which does NOT earn points?",
 opts:["Correct graph type","Axis labels with units","A title","Data plotted accurately with error bars"],a:2,
 why:"The three scored elements are graph type, labels (with units), and data + error bars. No points for a title.",
 wrong:{0:"Graph type is one of the three points.",1:"Labels with units is one of the three points.",3:"Plotting with error bars is one of the three points."}},
{id:"f7",t:"frq",q:"Which axis holds the independent variable, and which the dependent?",
 opts:["x = dependent; y = independent","x = independent; y = dependent","either, as long as labeled","x = time always"],a:1,
 why:"What you changed or grouped (independent) goes on x; what you measured (dependent, with units and error bars) goes on y.",
 wrong:{0:"Reversed.",2:"Convention matters for credit.",3:"Time is often the independent variable but not always."}},
{id:"f8",t:"frq",q:"If you are running out of time on the FRQ section, the teacher's '2-minute drill' says to",
 opts:["finish writing your current Explain answer perfectly","skip to the remaining Identify and Predict parts, which are fast 1-point answers","recopy the prompts so the grader knows what you read","leave the rest blank"],a:1,
 why:"Identify and Predict take seconds and are worth the same 1 point as a long Explain. Blanks are guaranteed zeros.",
 wrong:{0:"Perfecting one part while leaving quick points on the table is a bad trade.",2:"Restating prompts earns nothing.",3:"An attempt might score; a blank never does."}},
{id:"f9",t:"frq",q:"When asked to compare two groups in a data set, a full-credit answer",
 opts:["describes the higher group only","addresses BOTH groups explicitly and states the direction of the difference","reports the mean of one group with units","says 'they are different'"],a:1,
 why:"Make complete comparisons — address both groups, say which is higher/lower, include units and directionality.",
 wrong:{0:"Both groups must be addressed.",2:"One number isn't a comparison.",3:"Vague statements earn nothing."}},
{id:"f10",t:"frq",q:"In an experiment testing whether herbivore presence selects for higher trichome density, the independent variable is",
 opts:["trichome density","presence or absence of herbivores","plant height","number of plants sampled"],a:1,
 why:"The independent variable is what the experimenter manipulates (herbivores present vs absent). Trichome density is the dependent variable measured.",
 wrong:{0:"That's the dependent (measured) variable.",2:"Not part of the hypothesis.",3:"That's sample size."}},
{id:"f11",t:"frq",q:"Which is an appropriate CONTROL for the herbivore–trichome experiment?",
 opts:["Plants exposed to herbivores in a warmer greenhouse","Plants of the same species grown identically but with no herbivores","Plants of a different species with herbivores","No plants at all"],a:1,
 why:"A control differs from the treatment in only the independent variable — same species, same conditions, no herbivores.",
 wrong:{0:"Changes two variables (herbivores AND temperature).",2:"Changes species — confounding.",3:"Provides no comparison."}},
];

// FRQ: {id, t, prompt(html), parts:[{verb, text, pts, rubric:[strings]}]}
const FRQ = [
{id:"F1",t:"lipids",title:"Phospholipids and membranes",
 stem:"Phospholipids are the major component of plasma membranes.",
 parts:[
  {verb:"Describe",text:"the structure of a phospholipid.",pts:2,rubric:["Glycerol + 2 fatty acids + a phosphate group","Has a polar/hydrophilic head (phosphate) AND nonpolar/hydrophobic tails (fatty acids) — amphipathic"]},
  {verb:"Explain",text:"how this structure enables phospholipids to form a bilayer in water.",pts:2,rubric:["Like attracts like: polar heads orient toward water on both sides; nonpolar tails orient inward away from water (must give the WHY — polarity)","Result: a two-layer sheet with tails in the middle that separates the watery inside from outside (structure → function)"]}
 ]},
{id:"F2",t:"carbs",title:"Starch vs cellulose",
 stem:"Starch and cellulose are both polysaccharides made entirely of glucose monomers.",
 parts:[
  {verb:"Identify",text:"the type of bond that links glucose monomers in both polymers.",pts:1,rubric:["Glycosidic linkage (covalent)"]},
  {verb:"Describe",text:"ONE structural difference between starch and cellulose.",pts:1,rubric:["Starch has alpha linkages; cellulose has beta linkages (different orientation of the bond/shape of the chain)"]},
  {verb:"Explain",text:"why humans can digest starch but not cellulose.",pts:2,rubric:["Digestion requires enzymes that fit the specific linkage; humans have enzymes for alpha linkages","Humans lack enzymes for beta linkages, so cellulose passes through undigested as fiber (herbivores rely on gut bacteria)"]}
 ]},
{id:"F3",t:"proteins",title:"Enzyme in the wrong pH",
 stem:"An enzyme that normally functions at pH 7 is placed in a solution at pH 2.",
 parts:[
  {verb:"Predict",text:"the effect on the enzyme's activity.",pts:1,rubric:["Activity decreases / enzyme stops working (denatures)"]},
  {verb:"Justify",text:"your prediction.",pts:2,rubric:["Low pH (high H⁺) changes charges on R-groups, disrupting the hydrogen bonds and ionic bonds that hold 2°/3°/4° structure","Protein unfolds (denatures) → shape changes → active site no longer fits → structural change leads to functional change"]},
  {verb:"Identify",text:"the level of protein structure that is NOT affected, and state why.",pts:1,rubric:["Primary structure — peptide bonds are covalent and need enzymatic hydrolysis to break"]}
 ]},
{id:"F4",t:"proteins",title:"A single mutation",
 stem:"A mutation causes a polar amino acid in the middle of a polypeptide to be replaced by a nonpolar amino acid.",
 parts:[
  {verb:"Describe",text:"the effect on primary structure.",pts:1,rubric:["The amino acid sequence is changed (by definition)"]},
  {verb:"Explain",text:"how tertiary structure might be affected.",pts:2,rubric:["Tertiary structure depends on R-group interactions (H-bonds, ionic, hydrophobic, disulfide)","A nonpolar R-group cannot form the H-bond/ionic bond the polar one did and is pulled toward the hydrophobic interior → fold changes"]},
  {verb:"Predict",text:"the consequence for the protein's function.",pts:1,rubric:["Function is likely altered or lost because shape determines function"]}
 ]},
{id:"F5",t:"water",title:"Heating water vs ethanol",
 stem:"Equal volumes of water and ethanol were heated with equal energy. After 10 minutes water reached 40 °C and ethanol reached 57 °C, starting from 20 °C.",
 parts:[
  {verb:"Describe",text:"the trend in the data for both liquids.",pts:1,rubric:["Both increase in temperature over time; ethanol increases faster/higher than water (address BOTH, with units: °C, min)"]},
  {verb:"Explain",text:"why water's temperature rose more slowly.",pts:2,rubric:["Water molecules are extensively hydrogen-bonded to each other","Added energy must first break H-bonds before increasing molecular motion (temperature) → high specific heat"]},
  {verb:"Identify",text:"ONE biological consequence of this property of water.",pts:1,rubric:["Any one: moderates coastal climates; stabilizes body/cell temperature; lakes and oceans resist temperature swings"]}
 ]},
{id:"F6",t:"build",title:"Building a dipeptide",
 stem:"Two amino acids are joined to form a dipeptide.",
 parts:[
  {verb:"Identify",text:"the type of reaction and the type of bond formed.",pts:1,rubric:["Dehydration synthesis (condensation); peptide bond (covalent)"]},
  {verb:"Describe",text:"what happens to the atoms of the functional groups involved.",pts:2,rubric:["The –OH of one amino acid's carboxyl group and an –H of the other's amino group are removed","They form one water molecule; a C–N bond forms between the carboxyl carbon and the amino nitrogen"]},
  {verb:"Explain",text:"why an indefinite number of different proteins can be built from only 20 amino acids.",pts:1,rubric:["Proteins vary in the length AND the sequence/order of amino acids; each different sequence folds into a different shape"]}
 ]},
{id:"F7",t:"nucleic",title:"DNA structure and function",
 stem:"DNA is a double-stranded antiparallel molecule whose two strands are held together by hydrogen bonds between complementary bases.",
 parts:[
  {verb:"Describe",text:"the three components of a nucleotide.",pts:1,rubric:["Phosphate group, 5-carbon sugar (deoxyribose), nitrogenous base"]},
  {verb:"Identify",text:"the bond that links nucleotides WITHIN a strand.",pts:1,rubric:["Phosphodiester bond (covalent)"]},
  {verb:"Explain",text:"how holding the two strands together with hydrogen bonds (rather than covalent bonds) is important to DNA's function.",pts:2,rubric:["H-bonds are individually weak, so the strands can be separated ('unzipped') without breaking the covalent backbone","This allows the bases to be accessed/read for replication and transcription, then the strands can re-pair"]}
 ]},
{id:"F8",t:"lipids",title:"Saturated vs unsaturated",
 stem:"Butter is solid at room temperature; olive oil is liquid.",
 parts:[
  {verb:"Describe",text:"the structural difference between saturated and unsaturated fatty acids.",pts:1,rubric:["Saturated: all single C–C bonds, straight chains, maximum H. Unsaturated: one or more C=C double bonds creating kinks"]},
  {verb:"Explain",text:"why one is solid and the other liquid at room temperature.",pts:2,rubric:["Straight saturated chains pack tightly with more contact between molecules → solid (butter, animal fat)","Kinked unsaturated chains cannot pack tightly → liquid (plant oils)"]},
  {verb:"Predict",text:"how adding more double bonds to a fat would change its melting point.",pts:1,rubric:["Lower melting point / more likely to be liquid"]}
 ]},
{id:"F9",t:"groups",title:"Functional groups and polarity",
 stem:"An amino acid has an amino group, a carboxyl group, and an R-group on its central carbon.",
 parts:[
  {verb:"Identify",text:"the charge each group carries when ionized in water.",pts:1,rubric:["Amino → –NH₃⁺ (positive, basic); carboxyl → –COO⁻ (negative, acidic)"]},
  {verb:"Explain",text:"how the R-group determines whether an amino acid is hydrophobic or hydrophilic.",pts:2,rubric:["R-groups made of only C and H (e.g., methyl) are nonpolar → hydrophobic","R-groups containing O or N (hydroxyl, amino, carboxyl) are polar or charged → hydrophilic; 'presence of O and N are clues for polar'"]},
  {verb:"Describe",text:"the role of the sulfhydryl group in protein structure.",pts:1,rubric:["Two –SH groups (cysteine) form a covalent disulfide bridge that stabilizes tertiary/quaternary structure"]}
 ]},
{id:"F10",t:"frq",title:"Trichome data (graph + design)",
 stem:"Students measured stem trichome density (trichomes/cm²) in three plant populations. Means ± SEM: Population I = 9 ± 1; II = 11 ± 1; III = 14 ± 1. Trichomes are thought to protect plants from herbivores.",
 parts:[
  {verb:"Construct",text:"an appropriately labeled graph of the means with 95% CI error bars (sketch it on paper, then check).",pts:3,rubric:["Bar graph (discontinuous data); x-axis: Population I, II, III; y-axis: Trichome density (# trichomes/cm²) ± 2 SEM — labels copied exactly, with units","Even scale anchored at 0; bars plotted at 9, 11, 14","Error bars: I 7–11, II 9–13, III 12–16 (mean ± 2 SEM); no title needed"]},
  {verb:"Identify",text:"the two populations most likely to differ significantly.",pts:1,rubric:["I and III (error bars 7–11 and 12–16 do not overlap)"]},
  {verb:"Justify",text:"your selection.",pts:1,rubric:["Their 95% confidence intervals do not overlap, so the difference in means is unlikely to be due to chance (cite the numbers)"]},
  {verb:"Identify",text:"the independent and dependent variables for an experiment testing whether herbivore presence selects for higher trichome density.",pts:1,rubric:["Independent: presence/absence of herbivores. Dependent: trichome density (trichomes/cm²)"]},
  {verb:"Describe",text:"an appropriate control.",pts:1,rubric:["Same plant species grown under identical conditions with NO herbivores present"]},
  {verb:"Predict",text:"results that would support the hypothesis.",pts:1,rubric:["Plants exposed to herbivores show higher trichome density over generations than the control"]}
 ]},
{id:"F11",t:"carbs",title:"Glycogen vs starch",
 stem:"Glycogen (animal storage) is more highly branched than amylose starch (plant storage).",
 parts:[
  {verb:"Identify",text:"the monomer of both polysaccharides.",pts:1,rubric:["Glucose"]},
  {verb:"Explain",text:"how glycogen's branching relates to its function in animals.",pts:2,rubric:["Enzymes hydrolyze glucose from the free ends of chains; more branches = more free ends","So glycogen releases glucose faster, matching animals' need for quick energy on demand (structure → function)"]},
  {verb:"Describe",text:"where glycogen is stored in the human body.",pts:1,rubric:["Liver and muscle"]}
 ]},
{id:"F12",t:"water",title:"Properties of water in living things",
 stem:"Water's polarity and hydrogen bonding give it several emergent properties.",
 parts:[
  {verb:"Explain",text:"why water is polar and how that leads to hydrogen bonding.",pts:2,rubric:["Oxygen is more electronegative, pulling shared electrons → O partially negative, H partially positive","The δ+ H of one water molecule attracts the δ− O of another → hydrogen bonds between molecules (up to 4 per molecule)"]},
  {verb:"Describe",text:"TWO properties of water and a biological example of each.",pts:2,rubric:["Any two with correct example: cohesion/surface tension (water strider); adhesion + cohesion (capillary action in xylem); high specific heat (coastal climate, body temperature); evaporative cooling (sweating); floating ice (insulating lakes, lake turnover); versatile solvent (dissolving ions/polar molecules in cells)"]}
 ]}
];

// ================= UNIT 2 — CELL STRUCTURE & FUNCTION =================
for (const k in TOPICS) if (!TOPICS[k].unit) TOPICS[k].unit = 1;
Object.assign(TOPICS, {
  u2cells: {unit:2, name:"Cells, cell theory & organelles (2.1)", short:"Organelles"},
  u2endo:  {unit:2, name:"Endomembrane system & protein path (2.1–2.2)", short:"Endomembrane"},
  u2cyto:  {unit:2, name:"Cytoskeleton, cilia & junctions (2.1)", short:"Cytoskeleton"},
  u2size:  {unit:2, name:"Cell size & SA:V ratio (2.2)", short:"SA:V"},
  u2mem:   {unit:2, name:"Plasma membrane structure (2.3)", short:"Membrane"},
  u2perm:  {unit:2, name:"Membrane permeability & cell wall (2.4)", short:"Permeability"}
});
const UNITS = {1:{name:"Unit 1 · Chemistry of Life"}, 2:{name:"Unit 2 · Cell Structure & Function"}};
// Which unit is being taught now, and which topics were taught most recently (Today session leans on these)
const CURRENT = {unit:2, newest:["u2mem","u2perm"], taughtThrough:"2.4", asOf:"Wed Sep 23"};
// Daily plan: one guide idea per day, and that day's session practices exactly that idea.
// guide = page + section anchor in the study guide. Update this list as new material arrives.
const PLAN = [
  {date:"2026-09-24", topic:"u2cells", idea:"Idea 1", title:"Cells: two basic designs",        guide:"unit2.html#i1"},
  {date:"2026-09-25", topic:"u2endo",  idea:"Idea 2", title:"Follow one protein",               guide:"unit2.html#i2"},
  {date:"2026-09-26", topic:"u2cyto",  idea:"Idea 3", title:"The cytoskeleton and junctions",   guide:"unit2.html#i3"},
  {date:"2026-09-27", topic:"u2size",  idea:"Idea 4", title:"Why cells stay small (SA:V)",      guide:"unit2.html#i4"},
  {date:"2026-09-28", topic:"u2mem",   idea:"Idea 5", title:"The membrane is Unit 1 chemistry", guide:"unit2.html#i5"},
  {date:"2026-09-29", topic:"u2perm",  idea:"Idea 6", title:"What gets through the membrane",   guide:"unit2.html#i6"},
  {date:"2026-09-30", topic:"mix",     idea:"Review", title:"Cell Quiz review: all six ideas",  guide:"unit2.html#check"}
];

MCQ.push(
// ---------- 2.1 CELLS & ORGANELLES ----------
{id:"u2c1",t:"u2cells",q:"Which statement is part of the cell theory?",
 opts:["All cells contain a nucleus","Cells come only from preexisting cells","All organisms are multicellular","Cells arise from nonliving matter"],a:1,
 why:"Schleiden and Schwann (1839): cells are the fundamental units of life, all organisms are made of one or more cells, and cells come only from preexisting cells. Implication: life is continuous.",
 wrong:{0:"Prokaryotic cells have no nucleus.",2:"Organisms are made of ONE or more cells — bacteria are single-celled.",3:"That's spontaneous generation — the opposite of cell theory."}},
{id:"u2c2",t:"u2cells",q:"A student wants to study the internal membranes of a mitochondrion in fine detail. Which tool is best?",
 opts:["Light microscope","Scanning electron microscope (SEM)","Transmission electron microscope (TEM)","Magnifying glass"],a:2,
 why:"TEM passes electrons through thin sections to show internal structures at ~2 nm resolution. SEM shows surface features.",
 wrong:{0:"Light microscopes resolve only ~0.2 µm — too coarse for membrane detail.",1:"SEM images surfaces, not internal structure.",3:"Far too little magnification."}},
{id:"u2c3",t:"u2cells",q:"Which structure is found in BOTH prokaryotic and eukaryotic cells?",
 opts:["Nucleus","Mitochondria","Ribosomes","Endoplasmic reticulum"],a:2,
 why:"All cells need to make proteins, so all have ribosomes and a plasma membrane. Prokaryotes lack membrane-bound organelles.",
 wrong:{0:"Prokaryotes keep DNA in a nucleoid region, not a nucleus.",1:"Mitochondria are membrane-bound — eukaryotes only.",3:"The ER is membrane-bound — eukaryotes only."}},
{id:"u2c4",t:"u2cells",q:"In a prokaryotic cell, the DNA is located in the",
 opts:["nucleus","nucleolus","nucleoid region","capsule"],a:2,
 why:"'Pro-karyote' = before nucleus. The DNA sits in the nucleoid region with no surrounding membrane.",
 wrong:{0:"Prokaryotes have no nucleus.",1:"The nucleolus is inside a eukaryotic nucleus and makes rRNA/ribosomes.",3:"The capsule is an outer protective layer."}},
{id:"u2c5",t:"u2cells",q:"Which structure helps a bacterium attach to surfaces?",
 opts:["Flagellum","Pili","Nucleoid","Ribosome"],a:1,
 why:"Pili attach prokaryotes to surfaces. Flagella move them; the capsule protects them.",
 wrong:{0:"Flagella are for movement.",2:"The nucleoid holds DNA.",3:"Ribosomes make proteins."}},
{id:"u2c6",t:"u2cells",q:"The nucleolus is the site of",
 opts:["lipid synthesis","rRNA and ribosome synthesis","ATP production","protein packaging"],a:1,
 why:"From the slides: nucleolus → rRNA and ribosome synthesis. The nucleus as a whole holds the genetic material.",
 wrong:{0:"Lipids are made in the smooth ER.",2:"ATP comes from mitochondria.",3:"Packaging happens in the Golgi."}},
{id:"u2c7",t:"u2cells",q:"Ribosomes are made of",
 opts:["phospholipids and cholesterol","rRNA and protein","DNA and protein","glycogen"],a:1,
 why:"Two subunits built from ribosomal RNA plus protein. Your teacher noted they act like enzymes even though they're mostly RNA — not all enzymatic function is protein-based.",
 wrong:{0:"Ribosomes have no membrane.",2:"DNA is in the nucleus, not in ribosomes.",3:"Glycogen is a storage carbohydrate."}},
{id:"u2c8",t:"u2cells",q:"In eukaryotic cells, ribosomes are found",
 opts:["only attached to the rough ER","only free in the cytosol","attached to the rough ER, free in the cytosol, and inside mitochondria and chloroplasts","only inside the nucleus"],a:2,
 why:"All three locations appear on the slide. The ones inside mitochondria and chloroplasts are evidence for endosymbiosis (2.11).",
 wrong:{0:"Free ribosomes also exist.",1:"Many are bound to the rough ER.",3:"Ribosomes are ASSEMBLED with help from the nucleolus but work in the cytoplasm."}},
{id:"u2c9",t:"u2cells",q:"Which organelle converts the chemical energy in glucose into ATP?",
 opts:["Chloroplast","Mitochondrion","Golgi apparatus","Lysosome"],a:1,
 why:"Mitochondria convert chemical energy from one form to another (glucose → ATP) in aerobic respiration. Your teacher specifically said NOT to call it 'the powerhouse' on an FRQ — describe the actual function.",
 wrong:{0:"Chloroplasts convert light energy into chemical energy (glucose).",2:"The Golgi modifies and packages proteins.",3:"Lysosomes digest."}},
{id:"u2c10",t:"u2cells",q:"Mitochondria and chloroplasts share which structural feature?",
 opts:["A single membrane","An outer membrane surrounding a folded inner membrane","A cell wall","No ribosomes"],a:1,
 why:"Both have a double membrane, with the inner one folded to increase surface area for reactions.",
 wrong:{0:"Both have two membranes.",2:"Cell walls surround whole cells, not organelles.",3:"Both contain their own ribosomes."}},
{id:"u2c11",t:"u2cells",q:"Which set of structures would you find in a plant cell but NOT an animal cell?",
 opts:["Mitochondria, ribosomes, nucleus","Cell wall, chloroplasts, large central vacuole","Golgi, lysosomes, rough ER","Plasma membrane, cytoskeleton, ribosomes"],a:1,
 why:"Cell wall, chloroplasts and a large central vacuole are the plant-only trio on the slides.",
 wrong:{0:"Both cell types have these.",2:"Both cell types have these (lysosomes are mainly animal, but the Golgi and ER are universal).",3:"Every eukaryotic cell has these."}},
{id:"u2c12",t:"u2cells",q:"The large central vacuole of a plant cell",
 opts:["produces ATP","stores water, chemicals or waste and can help the cell grow by absorbing water","synthesizes proteins","anchors organelles"],a:1,
 why:"It's a large membranous storage sac; absorbing water helps the plant cell grow, and it can play a lysosome-like role.",
 wrong:{0:"ATP comes from mitochondria.",2:"Proteins are made by ribosomes.",3:"Anchoring is done by intermediate filaments."}},
{id:"u2c13",t:"u2cells",q:"The cell is described as the smallest unit that",
 opts:["contains DNA","can carry out ALL the functions of life","has a membrane","can divide"],a:1,
 why:"Direct from the slides: the cell is the smallest unit capable of carrying out all the functions of life.",
 wrong:{0:"Viruses and organelles contain DNA but aren't alive on their own.",2:"Organelles have membranes too.",3:"Division alone isn't the defining idea."}},

// ---------- ENDOMEMBRANE SYSTEM ----------
{id:"u2e1",t:"u2endo",q:"The rough ER is 'rough' because it is",
 opts:["studded with ribosomes","covered in cholesterol","folded into cristae","lined with cell wall"],a:0,
 why:"Ribosomes on its surface make proteins that enter the RER — compartmentalizing protein production.",
 wrong:{1:"Cholesterol is inside membranes and isn't visible as texture.",2:"Cristae are the folds of the mitochondrial inner membrane.",3:"The cell wall is outside the plasma membrane."}},
{id:"u2e2",t:"u2endo",q:"Liver cells detoxify drugs and alcohol. Which organelle would you expect to be abundant in them?",
 opts:["Rough ER","Smooth ER","Chloroplasts","Central vacuole"],a:1,
 why:"Smooth ER: lipid and steroid synthesis, detoxification in liver cells, glycogen metabolism. No ribosomes.",
 wrong:{0:"The rough ER makes proteins.",2:"Animal cells don't have chloroplasts.",3:"The central vacuole is a plant structure."}},
{id:"u2e3",t:"u2endo",q:"Cells of the adrenal gland make large amounts of steroid hormones. Which organelle should be prominent?",
 opts:["Smooth ER","Rough ER","Lysosomes","Nucleolus"],a:0,
 why:"Steroids are lipids, and lipid/steroid synthesis happens in the smooth ER.",
 wrong:{1:"The rough ER makes proteins, not steroids.",2:"Lysosomes digest.",3:"The nucleolus makes ribosomes."}},
{id:"u2e4",t:"u2endo",q:"What is the correct path of a secreted protein?",
 opts:["Golgi → rough ER → vesicle → plasma membrane","Ribosome on rough ER → rough ER → transport vesicle → Golgi → vesicle → plasma membrane","Nucleus → Golgi → lysosome → plasma membrane","Smooth ER → mitochondria → Golgi → plasma membrane"],a:1,
 why:"This is the slide 23 question ('Describe the movement of a secretory protein'). Made by ribosomes on the RER, enters the RER, buds off in a transport vesicle, modified and packaged in the Golgi, shipped in a vesicle that fuses with the plasma membrane.",
 wrong:{0:"The Golgi comes AFTER the ER.",2:"Proteins aren't made in the nucleus, and lysosomes are a destination, not a stop.",3:"Mitochondria aren't part of the secretory pathway."}},
{id:"u2e5",t:"u2endo",q:"Which function belongs to the Golgi apparatus?",
 opts:["Synthesizing ATP","Concentrating, packaging and sorting proteins, including adding carbohydrates to them","Digesting old organelles","Making rRNA"],a:1,
 why:"The Golgi modifies (adds sugar chains → glycoproteins), packages and sorts proteins. In plants it also makes polysaccharides.",
 wrong:{0:"ATP is made in mitochondria.",2:"That's the lysosome.",3:"rRNA is made in the nucleolus."}},
{id:"u2e6",t:"u2endo",q:"Lysosomes originate from the ______ and contain ______.",
 opts:["nucleus; DNA","Golgi; hydrolytic enzymes","smooth ER; lipids","mitochondria; ATP"],a:1,
 why:"Lysosomes bud from the Golgi and hold hydrolytic (digestive) enzymes that break down nutrients and recycle damaged organelles — hydrolysis from Unit 1.",
 wrong:{0:"Lysosomes don't come from the nucleus.",2:"They don't come from the smooth ER.",3:"They don't come from mitochondria."}},
{id:"u2e7",t:"u2endo",q:"A cell has a defect that prevents its lysosomes from working. What would you expect?",
 opts:["It cannot make proteins","Damaged organelles and undigested material accumulate inside the cell","It cannot produce ATP","Its DNA cannot be copied"],a:1,
 why:"Lysosomes digest nutrients and recycle old or damaged organelles. Without them, waste builds up.",
 wrong:{0:"Ribosomes make proteins.",2:"ATP production is mitochondrial.",3:"DNA replication happens in the nucleus."}},
{id:"u2e8",t:"u2endo",q:"Glycoproteins on the cell surface, used for cell recognition, first pass through which organelle?",
 opts:["Rough ER","Lysosome","Mitochondrion","Nucleolus"],a:0,
 why:"All secreted proteins and most membrane proteins, including glycoproteins, pass through the rough ER (then the Golgi).",
 wrong:{1:"Lysosomes are an endpoint for digestion.",2:"Not part of the endomembrane system.",3:"Makes ribosomes, not glycoproteins."}},
{id:"u2e9",t:"u2endo",q:"Which description of the Golgi would earn credit on your teacher's FRQ?",
 opts:["The Golgi is like a post office","The Golgi is a stack of pancakes","The Golgi is a set of flattened membrane sacs that modifies, packages and sorts proteins","The Golgi is the powerhouse of the cell"],a:2,
 why:"Your teacher's rule: don't use analogies to describe structure or function — describe the actual structure and function.",
 wrong:{0:"An analogy — no credit.",1:"Her own example of what NOT to write.",3:"Wrong organelle, and still an analogy."}},
{id:"u2e10",t:"u2endo",q:"The nuclear envelope is",
 opts:["a single membrane with no openings","a double membrane with pores, continuous with the ER","made of peptidoglycan","found in prokaryotes"],a:1,
 why:"Structure: spherical, double membrane with pores, continuous with the endoplasmic reticulum.",
 wrong:{0:"It's a double membrane, with pores.",2:"Peptidoglycan is in bacterial cell walls.",3:"Prokaryotes have no nucleus."}},
{id:"u2e11",t:"u2endo",q:"Which organelles are part of the endomembrane system?",
 opts:["Nucleus (envelope), ER, Golgi, lysosomes, vesicles, vacuoles, plasma membrane","Mitochondria and chloroplasts","Ribosomes and cytoskeleton","Cell wall and capsule"],a:0,
 why:"These membranes are connected directly or by vesicles. Mitochondria and chloroplasts are separate — they're the energy-converting organelles.",
 wrong:{1:"These are energy-converting organelles, not endomembrane.",2:"Neither has a membrane.",3:"These are outside the plasma membrane."}},

// ---------- CYTOSKELETON / CILIA / JUNCTIONS ----------
{id:"u2k1",t:"u2cyto",q:"Which cytoskeletal element is a straight, hollow tube that moves chromosomes and vesicles?",
 opts:["Microfilament","Intermediate filament","Microtubule","Cell wall"],a:2,
 why:"Microtubules (starred on the slide): hollow tubes of globular protein; structure, chromosome movement, vesicle transport.",
 wrong:{0:"Microfilaments are solid actin rods that change cell shape.",1:"Intermediate filaments are ropelike and resist tension, anchoring organelles.",3:"Not part of the cytoskeleton."}},
{id:"u2k2",t:"u2cyto",q:"Microfilaments are made of ______ and function in ______.",
 opts:["tubulin; chromosome movement","actin; changing the cell's shape","keratin; photosynthesis","cellulose; cell walls"],a:1,
 why:"Solid helical rods of actin; cell structure and shape change.",
 wrong:{0:"That's microtubules.",2:"Wrong function entirely.",3:"Cellulose is a carbohydrate, not cytoskeleton."}},
{id:"u2k3",t:"u2cyto",q:"Cilia and eukaryotic flagella share which internal structure?",
 opts:["A 9 + 2 arrangement of microtubules","Solid actin rods","A double membrane","Peptidoglycan"],a:0,
 why:"Both are microtubules in a 9 + 2 arrangement; cilia are short and numerous, flagella long and whiplike.",
 wrong:{1:"Actin forms microfilaments.",2:"That's mitochondria and chloroplasts.",3:"Peptidoglycan is a bacterial cell-wall material."}},
{id:"u2k4",t:"u2cyto",q:"Dynein makes a cilium bend by",
 opts:["changing shape and sliding microtubule doublets, while nexin crosslinks keep them from sliding apart","digesting microtubules","pumping water into the cilium","binding to DNA"],a:0,
 why:"Dynein is a motor protein; its conformational change drives the sliding of doublets. Nexin holds the doublets together, so the sliding becomes a bend. Structure → function.",
 wrong:{1:"Nothing is digested.",2:"Movement isn't driven by water.",3:"Dynein works on microtubules, not DNA."}},
{id:"u2k5",t:"u2cyto",q:"Kinesin is a motor protein that",
 opts:["binds vesicles and 'walks' them along microtubules","forms tight junctions","makes ribosomes","synthesizes lipids"],a:0,
 why:"Your teacher's favorite: kinesin carries vesicles along microtubule tracks.",
 wrong:{1:"Tight junctions are membrane protein seals.",2:"The nucleolus makes ribosomes.",3:"The smooth ER synthesizes lipids."}},
{id:"u2k6",t:"u2cyto",q:"Which junction allows water and small molecules to pass directly between neighboring cells?",
 opts:["Tight junction","Desmosome","Gap junction (plasmodesmata in plants)","Capsule"],a:2,
 why:"Gap (communicating) junctions and plasmodesmata (starred on the slide) are small openings connecting neighboring cells.",
 wrong:{0:"Tight junctions seal cells into a leak-proof sheet.",1:"Desmosomes attach cells like Velcro.",3:"A capsule is a bacterial outer layer."}},
{id:"u2k7",t:"u2cyto",q:"The cells lining the intestine must keep digestive fluid from leaking between them. Which junction does that?",
 opts:["Gap junction","Tight junction","Plasmodesma","Desmosome"],a:1,
 why:"Tight junctions seal adjacent cells to form a leak-proof sheet.",
 wrong:{0:"Gap junctions are openings — the opposite of a seal.",2:"Plasmodesmata are plant channels.",3:"Desmosomes anchor cells but don't seal them."}},
{id:"u2k8",t:"u2cyto",q:"Which cytoskeletal element resists tension and anchors organelles in place?",
 opts:["Microtubules","Microfilaments","Intermediate filaments","Cilia"],a:2,
 why:"Intermediate filaments: ropelike fibrous proteins that anchor organelles, resist tension and maintain rigidity.",
 wrong:{0:"Microtubules move chromosomes and vesicles.",1:"Microfilaments change cell shape.",3:"Cilia are for movement and feeding."}},

// ---------- CELL SIZE & SA:V ----------
{id:"u2s1",t:"u2size",q:"As a cell grows larger, its surface-area-to-volume ratio",
 opts:["increases","decreases","stays the same","doubles"],a:1,
 why:"Volume grows faster (cubed) than surface area (squared), so SA:V decreases — highlighted on her slide.",
 wrong:{0:"Reversed.",2:"The two grow at different rates.",3:"It falls, not rises."}},
{id:"u2s2",t:"u2size",q:"Why are most cells small?",
 opts:["Small cells need less DNA","A high SA:V ratio lets materials diffuse in and wastes out efficiently for the cell's volume","Large cells cannot have organelles","Cell membranes cannot stretch"],a:1,
 why:"Everything enters and leaves through the membrane. A larger cell has relatively less membrane per volume, so exchange can't keep up.",
 wrong:{0:"DNA amount isn't the constraint here.",2:"Large cells can have organelles.",3:"Membrane stretch isn't the explanation."}},
{id:"u2s3",t:"u2size",q:"The lining of the small intestine is folded into villi and microvilli. The main advantage is",
 opts:["decreased volume","increased surface area for absorbing nutrients","increased rigidity","fewer cells needed"],a:1,
 why:"Her structure → function example: folding tremendously increases surface area for absorption.",
 wrong:{0:"The point is surface area, not volume.",2:"Folding isn't about rigidity.",3:"Not the function."}},
{id:"u2s4",t:"u2size",q:"Besides folding its membrane, what else can a growing cell do to restore a high SA:V ratio?",
 opts:["Divide","Grow larger","Lose its nucleus","Stop making proteins"],a:0,
 why:"Dividing produces two smaller cells, each with a higher SA:V ratio.",
 wrong:{1:"Growing lowers SA:V further.",2:"Irrelevant to SA:V.",3:"Irrelevant to SA:V."}},
{id:"u2s5",t:"u2size",q:"Elephant and mouse kidney cells are about the same size. The best explanation is that",
 opts:["elephants have fewer cells","cell size is limited by the need for an adequate SA:V ratio, so larger organisms have more cells, not larger ones","elephant cells lack organelles","kidney cells don't exchange materials"],a:1,
 why:"From the cell-size lab introduction: SA:V limits cell size, so a larger organism is built from more cells.",
 wrong:{0:"Elephants have far more cells.",2:"They have the usual organelles.",3:"Kidney cells exchange a lot of material."}},
{id:"u2s6",t:"u2size",q:"In the Decocube lab, which cube will have the greatest percentage of its volume reached by vinegar after 15 minutes?",
 opts:["The 2 cm cube","The 0.5 cm cube","Both the same","It depends on the vinegar temperature only"],a:1,
 why:"Vinegar penetrates to about the same depth in both cubes, but that depth is a much larger fraction of the small cube, whose SA:V is 12 versus 3.",
 wrong:{0:"The big cube has the lowest SA:V.",2:"Depth is similar, but % diffused is not.",3:"Temperature is held constant; size is the variable."}},
{id:"u2s7",t:"u2size",q:"In the Decocube lab, what is the independent variable?",
 opts:["Distance the vinegar penetrates","Cube size (and therefore SA:V ratio)","Time in the vinegar","Type of vinegar"],a:1,
 why:"You change the cube size. Distance penetrated / % diffused is the dependent variable (measured). Time and vinegar type are constants.",
 wrong:{0:"That's the dependent variable (with units: mm).",2:"Held constant at 15 minutes.",3:"Held constant."}},
{id:"u2s8",t:"u2size",q:"If smaller cells are more efficient, why aren't cells infinitely small?",
 opts:["Tiny cells have too much membrane","A cell must be large enough to hold DNA, ribosomes and the machinery for life","Small cells cannot divide","Small cells have low SA:V"],a:1,
 why:"Slide 45: there's a lower limit — the cell must hold everything needed to carry out all functions of life.",
 wrong:{0:"More membrane per volume is an advantage.",2:"Small cells divide fine.",3:"Small cells have a HIGH SA:V."}},

// ---------- 2.3 PLASMA MEMBRANE ----------
{id:"u2m1",t:"u2mem",q:"The 'fluid mosaic model' describes the membrane as",
 opts:["a rigid layer of protein","a phospholipid bilayer in which proteins and other components can move laterally, like a mosaic of many parts","two layers of protein with lipid between them","a carbohydrate wall"],a:1,
 why:"Fluid: phospholipids and proteins drift sideways. Mosaic: many different components — proteins, cholesterol, glycoproteins, glycolipids.",
 wrong:{0:"The membrane is fluid, not rigid.",2:"An old, rejected model.",3:"That describes a cell wall."}},
{id:"u2m2",t:"u2mem",q:"Why do phospholipids spontaneously form a bilayer in water?",
 opts:["Their tails are charged","Hydrophilic heads face the water on both sides while hydrophobic tails face each other — the most energetically favorable arrangement","Water is nonpolar","Proteins force them into place"],a:1,
 why:"Both the inside and outside of a cell are aqueous. Heads toward water, tails hidden — like attracts like from Unit 1.",
 wrong:{0:"The tails are nonpolar hydrocarbon.",2:"Water is polar.",3:"It happens without proteins."}},
{id:"u2m3",t:"u2mem",q:"Phospholipids are placed between a layer of oil (top) and water (bottom). How do they orient?",
 opts:["As a bilayer with tails in the middle","As a single layer: tails pointing up into the oil, heads down into the water","Heads up into the oil","They dissolve completely in the water"],a:1,
 why:"This is slide 9's third scenario. With oil on one side and water on the other, a single layer is enough: tails to the nonpolar oil, heads to the polar water.",
 wrong:{0:"A bilayer forms with water on BOTH sides.",2:"Polar heads avoid oil.",3:"The tails are hydrophobic."}},
{id:"u2m4",t:"u2mem",q:"At low temperatures, cholesterol in the membrane",
 opts:["decreases fluidity","increases fluidity by acting as a spacer that keeps phospholipid tails from packing tightly","has no effect","dissolves"],a:1,
 why:"Cholesterol's effect is temperature-dependent: a spacer in the cold (↑ fluidity), a restraint in the heat (↓ fluidity).",
 wrong:{0:"That's its effect at WARM temperatures.",2:"It has an effect in both directions.",3:"Cholesterol is a stable lipid in the membrane."}},
{id:"u2m5",t:"u2mem",q:"At warm temperatures, cholesterol",
 opts:["decreases fluidity by interacting with multiple phospholipid tails","increases fluidity","makes the membrane permeable to ions","breaks phospholipids apart"],a:0,
 why:"By holding onto neighboring tails, cholesterol restrains their movement and keeps the membrane from becoming too fluid.",
 wrong:{1:"That's its effect in the cold.",2:"It doesn't open the membrane to ions.",3:"It doesn't break phospholipids."}},
{id:"u2m6",t:"u2mem",q:"Glycoproteins and glycolipids on the outer surface of the membrane function mainly in",
 opts:["ATP production","cell recognition ('ID tags')","lipid synthesis","transporting water"],a:1,
 why:"'Glyco' = carbohydrate chain. Attached to a protein → glycoprotein; to a phospholipid head → glycolipid. Both act as identity markers.",
 wrong:{0:"Mitochondria make ATP.",2:"The smooth ER does that.",3:"Aquaporins transport water."}},
{id:"u2m7",t:"u2mem",q:"An integral protein spans the membrane. The part of it inside the bilayer most likely has",
 opts:["polar, hydrophilic amino acids","nonpolar, hydrophobic amino acids","only charged amino acids","no amino acids"],a:1,
 why:"The middle of the bilayer is the nonpolar tail region, so the protein segment there has nonpolar R-groups. The parts sticking into the water are polar. Unit 1 R-groups meet Unit 2.",
 wrong:{0:"Those face the watery environment.",2:"Charged groups would be repelled by the tail region.",3:"Proteins are made of amino acids."}},
{id:"u2m8",t:"u2mem",q:"A protein on the surface of a liver cell binds insulin, triggering a response inside the cell. This protein is acting as a",
 opts:["channel","receptor","cell-adhesion molecule","enzyme"],a:1,
 why:"Receptors bind chemical messengers such as hormones sent by other cells.",
 wrong:{0:"Channels let solutes through.",2:"Adhesion molecules bind neighboring cells.",3:"Enzymes catalyze reactions."}},
{id:"u2m9",t:"u2mem",q:"Which type of membrane protein sits on the inner or outer surface without passing into the bilayer?",
 opts:["Integral","Peripheral","Channel","Aquaporin"],a:1,
 why:"Peripheral proteins sit on the surface. Integral proteins are embedded, partly or all the way through.",
 wrong:{0:"Integral proteins are embedded.",2:"Channels pass through the membrane.",3:"Aquaporins are water channels through the membrane."}},
{id:"u2m10",t:"u2mem",q:"Internal membranes in eukaryotic cells are an advantage because they",
 opts:["make the cell smaller","create compartments so different reactions can happen at the same time, and increase surface area for reactions","remove the need for a plasma membrane","prevent protein synthesis"],a:1,
 why:"Compartmentalization: each organelle can maintain its own internal environment, and folded membranes add surface area.",
 wrong:{0:"Not the purpose.",2:"All cells still need a plasma membrane.",3:"Compartments help protein synthesis (RER)."}},

// ---------- 2.4 PERMEABILITY & CELL WALL ----------
{id:"u2p1",t:"u2perm",q:"Which molecule crosses the lipid bilayer most easily without help?",
 opts:["Glucose","Na⁺","O₂","Proteins"],a:2,
 why:"Small and nonpolar: O₂, CO₂ and N₂ pass directly between the lipids.",
 wrong:{0:"Large and polar — needs a channel or carrier.",1:"Ions are charged and repelled by the nonpolar tails.",3:"Far too large."}},
{id:"u2p2",t:"u2perm",q:"Sodium ions (Na⁺) cross the membrane mainly",
 opts:["directly between the lipids","through channel or transport proteins","by dissolving in the tails","they cannot cross at all"],a:1,
 why:"Ions are charged; the hydrophobic core blocks them, so they need proteins.",
 wrong:{0:"Charge blocks direct passage.",2:"Charged ions don't dissolve in nonpolar tails.",3:"They cross — with protein help."}},
{id:"u2p3",t:"u2perm",q:"Water crosses the membrane",
 opts:["only through aquaporins","in small amounts between the lipids and in large amounts through aquaporins","never","only with ATP"],a:1,
 why:"Water is small but polar: a little slips between lipids; aquaporin channels carry the bulk.",
 wrong:{0:"Some also passes between lipids.",2:"Water crosses constantly.",3:"Water movement is passive."}},
{id:"u2p4",t:"u2perm",q:"In the POGIL, urea crossed the membrane more easily than glucose. The best explanation is that urea is",
 opts:["nonpolar","smaller","charged","a lipid"],a:1,
 why:"Both are polar, but urea is much smaller, so it slips through more easily. Size matters alongside polarity.",
 wrong:{0:"Urea is polar.",2:"Urea is uncharged.",3:"Urea isn't a lipid."}},
{id:"u2p5",t:"u2perm",q:"Steroid hormones can cross the membrane without a protein because they are",
 opts:["charged","nonpolar (lipids)","very small ions","polar sugars"],a:1,
 why:"Large but nonpolar: steroids pass (slowly) between the lipids. Like dissolves like.",
 wrong:{0:"Steroids are uncharged.",2:"Steroids are large organic molecules.",3:"Steroids are lipids, not sugars."}},
{id:"u2p6",t:"u2perm",q:"'Selectively permeable' means the membrane",
 opts:["lets everything through","lets nothing through","lets some substances cross more easily than others","only lets water through"],a:2,
 why:"Size and polarity decide what crosses freely; proteins control the rest. That selectivity maintains homeostasis.",
 wrong:{0:"Ions and large polar molecules are blocked without proteins.",1:"Small nonpolar molecules cross freely.",3:"Gases and nonpolar molecules cross too."}},
{id:"u2p7",t:"u2perm",q:"Diffusion of O₂ into a cell is passive, meaning",
 opts:["it requires ATP","it moves from high to low concentration without energy input from the cell","it moves against the concentration gradient","it requires a vesicle"],a:1,
 why:"From the POGIL: diffusion is driven by random molecular movement from high to low concentration — no energy needed.",
 wrong:{0:"Passive = no ATP.",2:"Against the gradient is active transport.",3:"Vesicles are bulk transport."}},
{id:"u2p8",t:"u2perm",q:"When a channel protein helps glucose move from high to low concentration, the process is",
 opts:["active transport","facilitated diffusion","simple diffusion","endocytosis"],a:1,
 why:"Passive (down the gradient) but needs a protein: facilitated diffusion. Coming up in 2.5–2.8.",
 wrong:{0:"Active transport uses ATP to move AGAINST the gradient.",2:"Simple diffusion needs no protein.",3:"Endocytosis uses vesicles."}},
{id:"u2p9",t:"u2perm",q:"The inside lining of a channel that carries ions is most likely",
 opts:["nonpolar","polar or charged","made of cholesterol","made of carbohydrate"],a:1,
 why:"POGIL Q10: ions are charged, so the channel's inner surface must be polar to let them through.",
 wrong:{0:"A nonpolar lining would repel ions.",2:"Channels are proteins.",3:"Channels are proteins."}},
{id:"u2p10",t:"u2perm",q:"Plant, fungal and prokaryotic cell walls are alike in that they",
 opts:["are made of phospholipids","are made of complex carbohydrates and provide structure while helping regulate what crosses","are identical in chemical makeup","exist only in plants"],a:1,
 why:"All cell walls are made of complex carbs (cellulose, chitin, peptidoglycan) and have a similar function: structure and permeability.",
 wrong:{0:"That's the plasma membrane.",2:"Their chemistry differs (cellulose vs chitin vs peptidoglycan).",3:"Fungi and prokaryotes have them too."}},
{id:"u2p11",t:"u2perm",q:"Which molecule would need a membrane protein to cross the membrane?",
 opts:["N₂","CO₂","Bicarbonate ion (HCO₃⁻)","O₂"],a:2,
 why:"POGIL extension Q14: bicarbonate is charged, so it can't cross the hydrophobic core freely. The gases are small and nonpolar.",
 wrong:{0:"Small nonpolar gas — crosses freely.",1:"Small nonpolar gas — crosses freely.",3:"Small nonpolar gas — crosses freely."}},

// ---------- NUMERIC (type in the answer) ----------
{id:"u2n1",t:"u2size",type:"num",q:"A cube-shaped cell is 2 cm on each side. What is its surface-area-to-volume ratio? (Formula sheet: SA = 6s², V = s³)",
 answer:3, tol:0.05, unit:"(per cm)",
 why:"SA = 6 × 2² = 24 cm². V = 2³ = 8 cm³. SA:V = 24 ÷ 8 = 3.",
 hint:"Compute SA and V separately first, then divide SA by V."},
{id:"u2n2",t:"u2size",type:"num",q:"A cube-shaped cell is 0.5 cm on each side. What is its SA:V ratio?",
 answer:12, tol:0.05, unit:"(per cm)",
 why:"SA = 6 × 0.5² = 1.5 cm². V = 0.5³ = 0.125 cm³. SA:V = 1.5 ÷ 0.125 = 12. That's 4× the 2 cm cube, which is why it diffuses so much faster in the Decocube lab.",
 hint:"0.5² = 0.25 and 0.5³ = 0.125."},
{id:"u2n3",t:"u2size",type:"num",q:"A spherical cell has a radius of 3 µm. What is its SA:V ratio? (SA = 4πr², V = 4/3 πr³)",
 answer:1, tol:0.02, unit:"(per µm)",
 why:"SA = 4π(9) ≈ 113.1 µm². V = 4/3 π(27) ≈ 113.1 µm³. SA:V = 1. Shortcut: for a sphere SA:V = 3/r = 3/3 = 1.",
 hint:"Divide the formulas before plugging in: (4πr²)/(4/3 πr³) = 3/r."},
{id:"u2n4",t:"u2size",type:"num",q:"A 2 cm Decocube soaks in vinegar and the vinegar penetrates 0.5 cm in from every face. What percent of the cube's volume has the vinegar reached?",
 answer:87.5, tol:0.5, unit:"%",
 why:"The unreached core is a cube 2 − 0.5 − 0.5 = 1 cm per side, so 1 cm³. Total = 8 cm³. Reached = 7 cm³. 7 ÷ 8 = 87.5%.",
 hint:"Subtract the penetration depth from BOTH sides to find the untouched inner cube."},
{id:"u2n5",t:"u2size",type:"num",q:"A 5 mm cube (SA = 150 mm²) is cut into 64 identical cubes, each 1.25 mm on a side. What is the TOTAL surface area of the 64 cubes, in mm²?",
 answer:600, tol:1, unit:"mm²",
 why:"Each small cube: 6 × 1.25² = 9.375 mm². × 64 = 600 mm². Same volume, four times the surface — the slide 42 example.",
 hint:"Find one small cube's SA, then multiply by 64."},
{id:"u2n6",t:"u2size",type:"num",q:"A cell's side length doubles (a cube going from 1 µm to 2 µm). By what factor does its SA:V ratio change? (Enter as a decimal, e.g. 0.25)",
 answer:0.5, tol:0.01, unit:"×",
 why:"1 µm cube: SA:V = 6/1 = 6. 2 µm cube: SA:V = 24/8 = 3. It halves. For a cube SA:V = 6/s, so doubling s halves the ratio.",
 hint:"For a cube, SA:V simplifies to 6/s."}
);

FRQ.push(
{id:"U2F1",t:"u2endo",title:"The path of a secreted protein",
 stem:"Pancreatic cells secrete large amounts of digestive enzymes, which are proteins.",
 parts:[
  {verb:"Identify",text:"the organelle where these enzymes are synthesized.",pts:1,rubric:["Ribosomes on the rough ER (accept: rough ER)"]},
  {verb:"Describe",text:"the path the enzymes take from synthesis to leaving the cell.",pts:2,rubric:["RER → transport vesicle → Golgi apparatus (modified/packaged/sorted)","Golgi → secretory vesicle → fuses with plasma membrane → released outside the cell (exocytosis)"]},
  {verb:"Predict",text:"how the amount of rough ER in a pancreatic cell compares with a cell that secretes little protein.",pts:1,rubric:["Pancreatic cells have MORE rough ER (compare both cells)"]}
 ]},
{id:"U2F2",t:"u2size",title:"Why cells stay small",
 stem:"Students soaked a 2 cm Decocube and a 0.5 cm Decocube in vinegar for 15 minutes. Vinegar reached 87.5% of the 2 cm cube's volume and 100% of the 0.5 cm cube's volume.",
 parts:[
  {verb:"Identify",text:"the independent and dependent variables.",pts:1,rubric:["Independent: cube size / SA:V ratio. Dependent: % of volume diffused (or penetration distance in mm)"]},
  {verb:"Calculate",text:"the SA:V ratio of each cube.",pts:1,rubric:["2 cm: 24/8 = 3; 0.5 cm: 1.5/0.125 = 12 (with units per cm)"]},
  {verb:"Explain",text:"how the data support the claim that cells must remain small.",pts:2,rubric:["The smaller cube, with the higher SA:V (12 vs 3), was more completely diffused (100% vs 87.5%) — cite the data for BOTH cubes","Cells exchange nutrients and wastes across the membrane; as size increases SA:V decreases, so exchange can't keep up with the cell's volume"]}
 ]},
{id:"U2F3",t:"u2mem",title:"Cholesterol and temperature",
 stem:"Cholesterol is a steroid found between the phospholipids of animal cell membranes.",
 parts:[
  {verb:"Describe",text:"the effect of cholesterol on membrane fluidity at warm temperatures and at cold temperatures.",pts:2,rubric:["Warm: decreases fluidity (restrains phospholipid movement by interacting with multiple tails)","Cold: increases fluidity (acts as a spacer, preventing tails from packing tightly)"]},
  {verb:"Explain",text:"why maintaining membrane fluidity matters to the cell.",pts:1,rubric:["Membrane proteins and phospholipids must be able to move to function (fluid mosaic); too rigid or too fluid disrupts transport and selective permeability → homeostasis"]},
  {verb:"Predict",text:"what would happen to a membrane with no cholesterol at a very low temperature.",pts:1,rubric:["It would become too rigid/solidify (tails pack tightly), reducing function"]}
 ]},
{id:"U2F4",t:"u2perm",title:"What crosses the membrane",
 stem:"A researcher places O₂, glucose, Na⁺ and a steroid hormone on one side of an artificial phospholipid bilayer with NO proteins.",
 parts:[
  {verb:"Identify",text:"which two substances will cross the bilayer.",pts:1,rubric:["O₂ and the steroid hormone"]},
  {verb:"Explain",text:"why glucose and Na⁺ do not cross.",pts:2,rubric:["The bilayer's interior is made of nonpolar/hydrophobic fatty-acid tails","Na⁺ is charged and glucose is large and polar, so they are repelled by / can't pass the hydrophobic core"]},
  {verb:"Describe",text:"one change to the artificial membrane that would allow glucose to cross, and the direction it would move.",pts:1,rubric:["Add a channel/transport protein (facilitated diffusion); glucose moves from high to low concentration"]}
 ]}
);
